- build.gradle
- Fixed #6 
- Run the unit test.
- Create new app with this lib to confirm.
> Issue #6: Android library config is invalid

- build.gradle
- Fixed #8 
* Run the unit test.
* タスクの実行ログ
- BEFORE
```
10:11:01: Executing task 'clearJar'...
Executing tasks: [clearJar] in project /Users/dinh.thuy.duong/Documents/dev/ncmb_kotlin
> Task :clearJar UP-TO-DATE
BUILD SUCCESSFUL in 1s
1 actionable task: 1 up-to-date
10:11:03: Task execution finished 'clearJar'.
```
- AFTER
```
10:11:46: Executing task 'clearJar'...
Executing tasks: [clearJar] in project /Users/dinh.thuy.duong/Documents/dev/ncmb_kotlin
> Task :clearJar
BUILD SUCCESSFUL in 468ms
1 actionable task: 1 executed …
```
> Update clearJar task

- src/main/java/com/nifcloud/mbaas/core/NCMB.kt
> リリースの準備 v0.1.1

- README.md
> fix readme for need import sync plugin

- README.md
> fix readme for mistake

- gradle.properties
- src/main/java/com/nifcloud/mbaas/core/NCMBObject.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBObjectService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBUser.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBUserService.kt
- src/test/assets/yaml/mbaas.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBUserTest.kt
> fix user method composition

- src/main/java/com/nifcloud/mbaas/core/NCMBCallback.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBObjectService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBQuery.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBServiceInterface.kt
- src/test/assets/yaml/mbaas.yml
- src/test/assets/yaml/mbaas_error.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorQueryTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBQueryTest.kt
> カウント機能を追加（同期＋非同期）

- README.md
- src/main/java/com/nifcloud/mbaas/core/NCMBBase.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBGeoPoint.kt
- src/test/assets/json/valid_post_geopoint_response.json
- src/test/assets/json_error/valid_post_geopoint_error_response.json
- src/test/assets/yaml/mbaas.yml
- src/test/assets/yaml/mbaas_error.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorGeoPointTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBGeoPointTest.kt
> feature add geopoint

- README.md
- src/main/java/com/nifcloud/mbaas/core/NCMB.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBFirebaseMessagingService.kt
> fix readme for push

- README.md
> fix readme for user async

- src/main/java/com/nifcloud/mbaas/core/NCMBUser.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBUserService.kt
- currentUserのstatic化(companion objectに含める)
- companion objectの特性上、NCMBUserService内のcurrentUserの使用法の変更
> currentUserのstatic化

- src/main/java/com/nifcloud/mbaas/core/NCMBBase.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBInstallation.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBInstallationService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBObject.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- currentInstallation/currentUserを用いて、更新後にlocalデータが上着され、objectIdがなくなり、それ以降更新ができなくなってしまう現象が発生しています。
- 検証コード: onCreate処理
```kt
NCMB.initialize(this.getApplicationContext(),"APPKEY","CLIENTKEY");
//ここに記載
NCMB.initializePush(this.getApplicationContext())
var curInstallation = NCMBInstallation.currentInstallation
print("CurrentInstallation: " +curInstallation.deviceToken)
//　Userインスタンスの生成
var user = NCMBUser()
//ユーザー名・パスワードを設定
user.userName = "test" /* ユーザー名 */
user.password = "test" /* パスワード */
// ログイン …
```
> currentInstallation, currentUserの更新時にデータが上書きされる不具合修正

- src/main/java/com/nifcloud/mbaas/core/NCMBBase.kt
- src/test/assets/json/valid_get_geopoint_response.json
- src/test/assets/json_error/valid_get_geopoint_error_response.json
- src/test/assets/yaml/mbaas_error.yml
- src/test/assets/yaml/mbaas_geopoint.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorGeoPointTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBGeoPointTest.kt
> add geo query

- src/main/java/com/nifcloud/mbaas/core/NCMBPushService.kt
> Update internal for NCMBPushService

- src/main/java/com/nifcloud/mbaas/core/NCMBInstallationService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBObjectService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBService.kt
> fix RequestParamsAsync to RequestParams

- src/main/java/com/nifcloud/mbaas/core/NCMBConstant.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBGeoPoint.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBQuery.kt
- src/test/assets/json/valid_search_response_geodata.json
- src/test/assets/yaml/mbaas_query.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBQueryTest.kt
- 位置情報関連の検索
https://mbaas.nifcloud.com/doc/current/rest/common/query.html#%E4%BD%8D%E7%BD%AE%E6%83%85%E5%A0%B1%E6%A4%9C%E7%B4%A2
- whereWithinGeoBox()
```kt
val southwest = NCMBGeoPoint(10.0, 20.0)
val northeast = NCMBGeoPoint(30.0, 40.0)
val query = NCMBQuery.forObject("TestClassGeo")
query.whereWithinGeoBox("geo", southwest, northeast)
query.findInBackground (NCMBCallback { e, objects ->
if (e != null) {
//エラー時の処理
println( "検索に失敗しました。エラー:" + e.message)
} else {
//成功時の処理
println("検索に成功しました。")
if(objects is List<*>) {
for (obj:Any? in objects) {
if (obj is NCMBObject) {
println(obj.getObjectId())
println(obj.getGeo("geo").mlatitude)
println(obj.getGeo("geo").mlongitude)
}
}
}
}
})
```
- whereNearSphere()
```kt
val location = NCMBGeoPoint(10.0, 10.1)
val query = …
```
> 位置情報データ検索機能を追加

- src/main/java/com/nifcloud/mbaas/core/NCMBInstallation.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorInstallationTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorUserTest.kt
> delete save method

- src/main/java/com/nifcloud/mbaas/core/NCMBScript.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBScriptService.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBScriptTest.kt
> Add test code for script construct method

- src/main/java/com/nifcloud/mbaas/core/NCMBConnection.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBException.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBFile.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBFileService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBInstallationService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBObjectService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBPushService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBRequest.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBResponse.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBResponseBuilder.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBUserService.kt
- src/test/assets/json/valid_get_file.txt
- src/test/assets/json/valid_save_file.json
- src/test/assets/json_error/E404001_error_response.json
- src/test/assets/json_error/E413001_error_response.json
- src/test/assets/json_error/E415001_error_response.json
- src/test/assets/yaml/mbaas_error.yml
- src/test/assets/yaml/mbaas_file.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBDispatcher.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorDispatcher.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorFileTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBFileTest.kt
- ファイルを保存する（同期処理・非同期処理）
- テスト＆Mock追加
- 利用イメージ
- 事前にファイルを作成
参考：https://developer.android.com/training/data-storage/app-specific#kotlin
```kt
val filename = "testKotlin.txt"
val fileContents = "Hello world!"
this.openFileOutput(filename, Context.MODE_PRIVATE).use {
it.write(fileContents.toByteArray())
}
``` 
- 非同期処理
```kt
val file = File(this.filesDir, filename)  //※こちらのthis.filesDir はアプリcontext（NCMB.initialize(this）で渡すもの）
val fileObj = NCMBFile("tempFile.txt")
fileObj.fileData = file  //こちらはjava.io.File のインスタンスを受け取ります
// ファイルストアへの登録を実施
fileObj.saveInBackground(NCMBCallback { e, ncmbFile ->
if (e != null) {
//保存に失敗した場合の処理
println("保存に失敗しました : " + e.code + " " + e.message)
} else {
val fileObj = ncmbFile  as NCMBFile
//保存に成功した場合の処理
println("保存に成功しました fileName:" + fileObj.fileName)
}
})
```
- …
> ファイル機能のベース（ファイル登録＋ダウンロード機能）

- FORDEVELOPER.md
> FORDEVELOPを更新

- src/main/java/com/nifcloud/mbaas/core/NCMBConnection.kt
- src/test/assets/json/valid_save_file_png.json
- src/test/assets/yaml/mbaas_file.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBDispatcher.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBFileTest.kt
- Fixed #78 
```Kotlin
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
// TODO Auto-generated method stub
super.onActivityResult(requestCode, resultCode, data)
if (data == null || data.extras == null) {
return
} else {
val bp = data.extras!!.get("data") as Bitmap
//******* NCMB file upload *******
val byteArrayStream = ByteArrayOutputStream()
bp.compress(Bitmap.CompressFormat.PNG, 0, byteArrayStream)
val dataByte = byteArrayStream.toByteArray()
val filename = "test.png"
this.openFileOutput(filename, Context.MODE_PRIVATE).use {
it.write(dataByte)
}
val file = File(this.filesDir, filename)
val fileObj = NCMBFile(filename)
fileObj.fileData = file
// ファイルストアへの登録を実施
fileObj.saveInBackground(NCMBCallback { e, ncmbFile ->
runOnUiThread {
if (e …
```
> fix issue #78

- src/main/java/com/nifcloud/mbaas/core/NCMBBase.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- Fixed #79 
```Kotlin
try {
val curUser = NCMBUser.currentuser
val now = Date()
curUser!!.put("lastLoginDate", now)
curUser.save()
} catch (e1: NCMBException) {
e1.printStackTrace()
}
```
> Fix put date format

- src/main/java/com/nifcloud/mbaas/core/NCMBPush.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBRichPush.kt
- src/test/assets/yaml/mbaas_push.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBPushTest.kt
- リッチプッシュ通知機能
- プッシュ通知登録のsearchCondition追加
> NCMBPush Feature/rich push notification and searchCondition

- src/main/java/com/nifcloud/mbaas/core/NCMBAcl.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBAclTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- テストコード追加
- internalメソッド変更
- メソッド説明コメントの補足
> ACL機能のテスト追加＋細かい修正

- src/main/java/com/nifcloud/mbaas/core/NCMBUser.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorUserTest.kt
- 会員登録、会員ログイン時のusername, passwordがないのチェック処理修正
- NCMBUserErrorのcurrentUserを削除する処理修正（Unit Test修正）
> NCMBUser処理＋テスト更新

- src/main/java/com/nifcloud/mbaas/core/NCMBConnection.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBFile.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBFileService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBQuery.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBResponseBuilder.kt
- src/test/assets/json/valid_search_file_one_response.json
- src/test/assets/yaml/mbaas.yml
- src/test/assets/yaml/mbaas_file.yml
- src/test/assets/yaml/mbaas_query.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorFileTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorUserTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBFileTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBQueryTest.kt
以下の機能を追加しました。ご確認お願い致します。
- ファイルのACL登録
- ファイルの更新（ACL更新のみ）
- ファイルの検索
> ファイル機能の残機能

- src/main/java/com/nifcloud/mbaas/core/NCMBScript.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBScriptService.kt
- src/test/assets/json_error/valid_get_script_notFound_response.json
- src/test/assets/yaml/mbaas_error.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorScriptTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBScriptTest.kt
- `NCMBScript.kt`に`execute`メソッドを追加
- `NCMBScriptService.kt`に`executeScript`メソッドを追加
- execute関連テストの追加
> スクリプト残機能(同期処理)開発

- src/main/java/com/nifcloud/mbaas/core/NCMBConnection.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBInstallationService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBObjectService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBRequest.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBScriptService.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBService.kt
- src/test/assets/json/valid_script_query_response.txt
- src/test/assets/yaml/mbaas_script.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBConnectionTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBScriptTest.kt
> Update script(header, params, query)

- src/main/java/com/nifcloud/mbaas/core/NCMBBase.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBInstallation.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBObject.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBPush.kt
- src/main/java/com/nifcloud/mbaas/core/NCMBUser.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBDispatcher.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBObjectTest.kt
- Fixed #80 
- データを登録・更新する際のcreateDate, updateDate, objectIdが指定される場合の処理を更新
> Update ignoreField check for NCMBBase and NCMBObject

- src/test/assets/yaml/mbaas_datastore.yml
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBObjectTest.kt
> 配列登録機能のテスト追加

- .github/workflows/reference.yml
- developブランチへpushが行われたらGithub Action上でリファレンスを生成、置き換えを行いcommitします
* forkしたPJにて動作確認を行っています
* https://github.com/tanaka-kokoro/ncmb_kotlin
* 同じreference.ymlをmaster,developに追加してあります
* リファレンスを書き換えたp-r:https://github.com/tanaka-kokoro/ncmb_kotlin/pull/4 上で、Actionsの結果としてdocsファイルの置き換えが行われています
* コミット：https://github.com/tanaka-kokoro/ncmb_kotlin/pull/4/commits/b0519258b661d571d25dae7d1d2df1e3fb9a4ced
* <img width="877" alt="スクリーンショット 2022-10-17 17 19 11" src="https://user-images.githubusercontent.com/114896458/196125666-a1dff96d-d5ea-4a …
> リファレンス生成・置換の自動化

- README.md
- 動作環境を更新します
- Android 13, API levels , Android studioを追加
> Android 13をサポートする

- .github/workflows/kotlin.yml
- master,developブランチにpushもしくはp-rされた際に起動するワークフローに、NCMB.jarの生成とArtifacts出力するステップを追加しました
Run the workflow
> NCMB.jar生成のワークフロー追加

- README.md
- NCMB.initializeをNCMB.initialize(this.applicationContext, "YOUR_APPLICATION_KEY", "YOUR_CLIENT_KEY")に統一しました
> NCMB.initializeをドキュメントと統一する

- build.gradle
- src/main/java/com/nifcloud/mbaas/core/NCMB.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBAclTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBConnectionTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBDateFormatTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBDispatcher.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorDispatcher.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorFileTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorGeoPointTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorInstallationTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorPushTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorQueryTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorScriptTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBErrorUserTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBFileTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBGeoPointTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBInstallationTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBObjectTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBPushTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBQueryTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBScriptTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBTest.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBUserTest.kt
- テストやコード上で、警告（Warning）が出ており、以下の内容を対応します
- var -> valの利用
- 変数名がかぶっているため更新
- RuntimeEnvironment.applicationが非推奨になっているため更新
- intArrayOf() が非推奨のため更新
- ?, !! の利用を修正
> KotlinSDKの警告対応

- src/main/java/com/nifcloud/mbaas/core/NCMBBase.kt
- src/test/java/com/nifcloud/mbaas/core/NCMBBaseTest.kt
- 以下のメソッドとそれに対するテストを追加
- getDate
- getInt
- getDouble
- getBoolean
- getJson
- getArray
> 各データ型に対するgetメソッドの追加

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- gradle を 7.4 に更新
- kotlin_version を 1.5.20 に更新
- レガシーな`apply plugin`から`plugins {}`に更新
- それに伴いバージョンを指定していなかったものは追加
- setting.gradleを更新
- https://developer.android.com/studio/build?hl=ja#settings-file
- 併せてbuild.gradleの内容を一部setting.gradleへ移動
> gradleをv7.4に更新, plugins{}を追加, kotlin_versionを1.5.20に更新
